FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# EventsRegistrySius

Polls is a simple API allowing consumers to view polls and vote in them.

## Questions Collection [/questions]

### List All Questions [GET]

+ Response 200 (application/json)

        [
            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 2048
                    }, {
                        "choice": "Python",
                        "votes": 1024
                    }, {
                        "choice": "Objective-C",
                        "votes": 512
                    }, {
                        "choice": "Ruby",
                        "votes": 256
                    }
                ]
            }
        ]

### Create a New Question [POST]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

        {
            "question": "Favourite programming language?",
            "choices": [
                "Swift",
                "Python",
                "Objective-C",
                "Ruby"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }

## Registro Paciente [/pacientes]

### Registro de pacientes [POST]

+ Request (application/json)

        {
            "codigoEmpresa" : "DUSOFT",
            "tipoDocumento" : "CC",
            "numeroDocumento" : "1077850026",
            "primerNombre" : "Nicolás",
            "segundoNombre" : "Rubén",
            "primerApellido" : "Caballero",
            "segundoApellido" : "Ortega",
            "fechaEvento" : "25/10/2016",
            "numeroIngreso" : 257588,
            "numeroEvolucion" : 123456,
            "tipoAtencion" : 1,
            "codigoPais" : 169,
            "codigoDepartamento" : 76,
            "codigoCiudad" : "001",
            "<codigoBarrio" : "",
            "direccion" : "CALLE 5 CON CARRERA 4",
            "telefono" : "3187561862",
            "telefono2" : "",
            "correoElectronico" : "helaman58@gmail.com",
            "fechaNacimiento" : "19880805",
            "estadoCivil" : "UL",
            "nivelEducativo" : "1",
            "grupoEtnico" : "6",
            "ocupacion" : "100",
            "nacionalidad" : 169,
            "sexo" : "M",
            "personaContactoTD" : "CC",
            "personaContactoND" : "1113653275",
            "personaContactoNombre" : "LUZ KARIME OCAMPO COBO",
            "codigoEPS" : "68498",
            "nombreEPS" : "DIRECCION MUNICIPAL DE SALUD DE OCAMONTE",
            "tiempoAtencion" : "20161012130805",
            "codigoPaisNaci" : 169,
            "codigoDepartamentoNaci" : 76,
            "codigoCiudadNaci" : "001"
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }